apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: robertdolibog/app_docker:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_USER
          value: "rober"
        - name: POSTGRES_DB
          value: "mydatabase"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_HOST
          value: "postgres"