apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer  # Or ClusterIP if you're within a cluster
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 5000  # Port exposed by the Service
      targetPort: 5000  # Port on the Pod to forward to