name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - workflow # for testing

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t stephanlindauer/clickediclick:$GITHUB_SHA ./app

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image
        run: docker push stephanlindauer/clickediclick:$GITHUB_SHA